apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: bztyuzr4c-nodejs 
  janus-idp.io/tekton: bztyuzr4c-nodejs
  backstage.io/kubernetes-id: bztyuzr4c-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bztyuzr4c-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml